"""Initial migration

Revision ID: ae374cff3c26
Revises: 
Create Date: 2024-08-14 00:44:14.000689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae374cff3c26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alternativa_Correta',
    sa.Column('id_alternativa_correta', sa.Integer(), nullable=False),
    sa.Column('texto_alternativa', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_alternativa_correta')
    )
    op.create_table('Status_Jogo',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('status_jogo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', 'id_jogo')
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=245), nullable=False),
    sa.Column('senha', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('Andar',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['nome'], ['Usuario.nome'], ),
    sa.PrimaryKeyConstraint('numero')
    )
    op.create_table('Jogo',
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('vidas', sa.Integer(), nullable=False),
    sa.Column('feito', sa.Boolean(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_jogo')
    )
    op.create_table('Questao',
    sa.Column('id_questao', sa.Integer(), nullable=False),
    sa.Column('texto_pergunta', sa.Text(), nullable=False),
    sa.Column('id_jogo', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('id_alternativa_correta', sa.Integer(), nullable=True),
    sa.Column('respondida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_alternativa_correta'], ['Alternativa_Correta.id_alternativa_correta'], ),
    sa.ForeignKeyConstraint(['id_jogo'], ['Jogo.id_jogo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['numero'], ['Andar.numero'], ),
    sa.PrimaryKeyConstraint('id_questao')
    )
    op.create_table('Alternativa',
    sa.Column('id_alternativa', sa.Integer(), nullable=False),
    sa.Column('texto_alternativa', sa.Text(), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_questao'], ['Questao.id_questao'], ),
    sa.PrimaryKeyConstraint('id_alternativa')
    )
    op.drop_table('alternativa')
    op.drop_table('andar')
    op.drop_table('questao')
    op.drop_table('jogo')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('nome')

    op.drop_table('usuario')
    op.drop_table('alternativa_correta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternativa_correta',
    sa.Column('id_alternativa_correta', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('texto_alternativa', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_alternativa_correta'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=245), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('nome', ['nome'], unique=True)

    op.create_table('jogo',
    sa.Column('id_jogo', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('vidas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('feito', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_jogo'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('questao',
    sa.Column('id_questao', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('texto_pergunta', mysql.TEXT(), nullable=True),
    sa.Column('id_jogo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('numero', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_alternativa_correta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('respondida', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_questao'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('andar',
    sa.Column('numero', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('concluido', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('numero'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('alternativa',
    sa.Column('id_alternativa', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('texto_alternativa', mysql.TEXT(), nullable=True),
    sa.Column('id_questao', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_alternativa'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_table('Alternativa')
    op.drop_table('Questao')
    op.drop_table('Jogo')
    op.drop_table('Andar')
    op.drop_table('Usuario')
    op.drop_table('Status_Jogo')
    op.drop_table('Alternativa_Correta')
    # ### end Alembic commands ###
